"""
compare_with_paper.py — compare new Katana eval metrics with a reference CSV.

The new metrics CSV (default: outputs/eval_downstream/metrics.csv) is generated by
evaluate_downstream.py. The reference CSV is whatever you regard as the "ground
truth" — typically the metrics output from your original Block 3 notebook (e.g.
``final_downstream_soh_results.csv`` from NewJournal_Final/).

Both files must share the same schema, in particular the columns:
    Task, Method, Model, MAE_mean, RMSE_mean, R2_mean, ...

For every (Task, Method, Model) triple the script prints absolute and relative
differences and tags rows by severity:

    ✓ < 2%   — well within CUDA non-determinism, equivalent
    ⚠ 2-5%   — acceptable noise from re-training, double-check ordering
    ✗ ≥ 5%   — real divergence, needs investigation

It also re-derives method rankings per (Task, Model) and reports any ranking
swaps in MAE — those are the most diagnostic signal: if rankings are preserved,
the paper's conclusions survive.

Usage
-----
    python scripts/katana/compare_with_paper.py
    python scripts/katana/compare_with_paper.py \\
        --new outputs/eval_downstream/metrics.csv \\
        --ref outputs/reference_metrics.csv
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

WARN_PCT = 2.0   # relative diff in % above which a row is yellow
ERR_PCT = 5.0    # relative diff in % above which a row is red

METRIC_COLS = ["MAE_mean", "RMSE_mean", "MAPE_mean", "R2_mean"]


def load_csv(path: Path) -> list[dict]:
    if not path.is_file():
        sys.exit(f"ERROR: file not found: {path}")
    with open(path, "r", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def key(row: dict) -> tuple[str, str, str]:
    return (row["Task"], row["Method"], row["Model"])


def safe_float(x: str) -> float:
    try:
        return float(x)
    except (TypeError, ValueError):
        return float("nan")


def rel_pct(new: float, ref: float) -> float:
    """Symmetric relative diff in %, robust to ref ≈ 0."""
    denom = max(abs(ref), abs(new), 1e-9)
    return 100.0 * (new - ref) / denom


def tag_severity(abs_pct: float) -> str:
    a = abs(abs_pct)
    if a < WARN_PCT:
        return "OK"
    if a < ERR_PCT:
        return "WARN"
    return "ERR"


def severity_icon(sev: str) -> str:
    return {"OK": "✓", "WARN": "⚠", "ERR": "✗"}[sev]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--new", type=Path,
                    default=Path("outputs/eval_downstream/metrics.csv"),
                    help="path to newly produced metrics CSV from Katana")
    ap.add_argument("--ref", type=Path,
                    default=Path("outputs/reference_metrics.csv"),
                    help="path to reference metrics CSV (original Block 3 result)")
    ap.add_argument("--metric", default="MAE_mean", choices=METRIC_COLS,
                    help="which metric to focus comparison on (default: MAE_mean)")
    args = ap.parse_args()

    new_rows = {key(r): r for r in load_csv(args.new)}
    ref_rows = {key(r): r for r in load_csv(args.ref)}

    common = sorted(set(new_rows) & set(ref_rows))
    only_new = sorted(set(new_rows) - set(ref_rows))
    only_ref = sorted(set(ref_rows) - set(new_rows))

    print("=" * 90)
    print(f"Comparing metrics  (focus: {args.metric})")
    print(f"  new: {args.new}")
    print(f"  ref: {args.ref}")
    print("=" * 90)
    print(f"common rows: {len(common)},  only-new: {len(only_new)},  only-ref: {len(only_ref)}")
    if only_ref:
        print(f"  (in reference but missing from new — first 3: {only_ref[:3]})")
    if only_new:
        print(f"  (in new but not in reference — first 3: {only_new[:3]})")

    # ------------------------- per-row diff -------------------------
    print()
    print("-" * 90)
    print(f"Per-row diff on {args.metric}")
    print("-" * 90)
    print(f"{'Task':<14}{'Method':<14}{'Model':<14}"
          f"{'ref':>10}{'new':>10}{'Δ%':>10}  ")
    counts = {"OK": 0, "WARN": 0, "ERR": 0}
    worst = []  # (abs_pct, key, ref, new)
    for k in common:
        ref_v = safe_float(ref_rows[k][args.metric])
        new_v = safe_float(new_rows[k][args.metric])
        d = rel_pct(new_v, ref_v)
        sev = tag_severity(d)
        counts[sev] += 1
        worst.append((abs(d), k, ref_v, new_v, d, sev))
        if sev != "OK":
            print(f"{k[0]:<14}{k[1]:<14}{k[2]:<14}"
                  f"{ref_v:>10.4f}{new_v:>10.4f}{d:>9.2f}%  {severity_icon(sev)} {sev}")

    print()
    print(f"Summary:  ✓ OK={counts['OK']}   ⚠ WARN={counts['WARN']}   ✗ ERR={counts['ERR']}")

    # ------------------------- top-5 divergences -------------------------
    worst.sort(reverse=True)
    print()
    print("-" * 90)
    print("Top 5 largest relative differences (any severity)")
    print("-" * 90)
    for _, k, ref_v, new_v, d, sev in worst[:5]:
        print(f"  {severity_icon(sev)} {k[0]:<13}{k[1]:<13}{k[2]:<13}"
              f"ref={ref_v:.4f}  new={new_v:.4f}  Δ={d:+.2f}%")

    # ------------------------- ranking preservation -------------------------
    # For each (Task, Model), rank methods by MAE_mean ascending. If the new
    # ranking differs from ref, that's a meaningful signal beyond raw diff%.
    print()
    print("-" * 90)
    print("Method-ranking preservation by (Task, Model) — MAE_mean ascending")
    print("-" * 90)

    def rank_table(rows: list[dict]) -> dict[tuple[str, str], list[str]]:
        by_tm: dict[tuple[str, str], list[tuple[float, str]]] = {}
        for r in rows:
            by_tm.setdefault((r["Task"], r["Model"]), []).append(
                (safe_float(r["MAE_mean"]), r["Method"])
            )
        return {k: [m for _, m in sorted(v)] for k, v in by_tm.items()}

    ref_rank = rank_table(load_csv(args.ref))
    new_rank = rank_table(load_csv(args.new))

    rank_problems = 0
    for tm in sorted(set(ref_rank) & set(new_rank)):
        if ref_rank[tm] != new_rank[tm]:
            rank_problems += 1
            print(f"  ⚠ {tm[0]}, {tm[1]}:")
            print(f"      ref: {ref_rank[tm]}")
            print(f"      new: {new_rank[tm]}")
    if rank_problems == 0:
        print("  ✓ All method rankings preserved — paper conclusions hold.")

    # ------------------------- verdict -------------------------
    print()
    print("=" * 90)
    if counts["ERR"] == 0 and rank_problems == 0:
        print("VERDICT: ✓ Equivalent (within CUDA non-determinism + retraining noise).")
        return 0
    elif counts["ERR"] == 0:
        print("VERDICT: ⚠ Numerically equivalent but some method rankings shifted.")
        print("         Worth a closer look at the swapped rows above.")
        return 0
    else:
        print("VERDICT: ✗ Some metrics differ by ≥ 5%. Investigate before publishing.")
        return 1


if __name__ == "__main__":
    sys.exit(main())
